name: Deploy to GAE

# Controls when the workflow will run
on:
  push:
    branches: 
      - server

  pull_request:
    branches:
      - server

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.2
      with:
        envkey_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        envkey_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        envkey_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
        envkey_FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
        envkey_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
        envkey_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        envkey_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        envkey_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        envkey_FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
        directory: 'APP(BE)'
        fail_on_empty: false

    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: 'APP(BE)/app.yaml'
        version: v1
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.GCP_CREDENTIALS }}

    - name: Test
      run: 'curl "${{ steps.deploy.outputs.url }}"'